services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: tracker-postgres
    environment:
      POSTGRES_DB: tracker_db
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    ports:
      - "5454:5432"
    volumes:
      - tracker_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - tracker_redis:/data

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: tracker-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: tracker-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  tracker_pg:
  tracker_redis:
  prometheus_data:
  grafana_data:
