services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: tracker-postgres
    environment:
      POSTGRES_DB: tracker_db
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    ports:
      - "5454:5432"
    volumes:
      - tracker_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - tracker_redis:/data

volumes:
  tracker_pg:
  tracker_redis:
